# Generated by Django 4.0.8 on 2022-11-18 09:56

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contests_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoscontests',
            name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='contests',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gallerynews',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='galleryproject',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='photosnews',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='photosproject',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='contests',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='Short_Description',
        ),
        migrations.RemoveField(
            model_name='photosnews',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='photosproject',
            name='Title',
        ),
        migrations.AddField(
            model_name='photosnews',
            name='Caption',
            field=models.CharField(default='', max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AddField(
            model_name='photosproject',
            name='Caption',
            field=models.CharField(default='', max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Document',
            field=models.FileField(upload_to=main.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Status',
            field=models.CharField(choices=[('Актуально', 'Актуально'), ('Проведён', 'Проведён'), ('Не Проведён', 'Не Проведён')], default='Актуально', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Title',
            field=models.CharField(max_length=180, verbose_name='Описание конкурса'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Short_Description',
            field=models.CharField(max_length=110, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='Gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='URL',
            field=models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.ImageField(upload_to=main.models.get_file_path, verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.projectcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Реализован', 'Реализован'), ('Не реализован', 'Не реализован')], default='В процессе', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='ContestsCategory',
        ),
        migrations.DeleteModel(
            name='GalleryContests',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='PhotosContests',
        ),
    ]
