# Generated by Django 4.0.8 on 2022-11-20 09:17

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_photoscontests_gallery_alter_contests_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=70, verbose_name='Компания')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения')),
                ('positions', models.CharField(max_length=70, verbose_name='Должность')),
                ('salary', models.CharField(max_length=70, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Актуально', 'Актуально'), ('Данная вакансия не актуальна', 'Данная вакансия не актуальна')], default='Актуально', max_length=30, verbose_name='Статус')),
                ('email_company', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={},
        ),
        migrations.AddField(
            model_name='contests',
            name='Short_Description',
            field=models.CharField(default='', max_length=110, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='Short_Description',
            field=models.CharField(default=' ', max_length=110, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='Caption',
            field=models.CharField(max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.FileField(upload_to=main.models.get_file_path, verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
